// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bridge} from '../models';
import {context} from '../models';

export function Greet(arg1:string):Promise<string>;

export function RepoRemoteReadCommits(arg1:string):Promise<Array<bridge.LogEntryInfo>>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
