// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['bridge']['App']['Greet'](arg1);
}

export function RepoRemoteReadCommits(arg1) {
  return window['go']['bridge']['App']['RepoRemoteReadCommits'](arg1);
}

export function Shutdown(arg1) {
  return window['go']['bridge']['App']['Shutdown'](arg1);
}

export function Startup(arg1) {
  return window['go']['bridge']['App']['Startup'](arg1);
}
