// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bridge} from '../models';
import {context} from '../models';

export function GetDarkTheme():Promise<bridge.Theme>;

export function GetLightTheme():Promise<bridge.Theme>;

export function SendText(arg1:string):Promise<void>;

export function SetTTYSize(arg1:number,arg2:number):Promise<void>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function Start():Promise<void>;

export function StartTTY():Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
