// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDarkTheme() {
  return window['go']['bridge']['TerminalApp']['GetDarkTheme']();
}

export function GetLightTheme() {
  return window['go']['bridge']['TerminalApp']['GetLightTheme']();
}

export function SendText(arg1) {
  return window['go']['bridge']['TerminalApp']['SendText'](arg1);
}

export function SetTTYSize(arg1, arg2) {
  return window['go']['bridge']['TerminalApp']['SetTTYSize'](arg1, arg2);
}

export function Shutdown(arg1) {
  return window['go']['bridge']['TerminalApp']['Shutdown'](arg1);
}

export function Start() {
  return window['go']['bridge']['TerminalApp']['Start']();
}

export function StartTTY() {
  return window['go']['bridge']['TerminalApp']['StartTTY']();
}

export function Startup(arg1) {
  return window['go']['bridge']['TerminalApp']['Startup'](arg1);
}
